version: 1
formatters:
  fmt_console:
    # full configuration of ColoredFormatter is possible - https://coloredlogs.readthedocs.io/en/latest/api.html#coloredlogs.ColoredFormatter
    (): coloredlogs.ColoredFormatter # () allows class instantiation with properties at the same level as constructor arguments.
    fmt: "%(levelname)s %(asctime)s %(name)s:      %(message)s"
    datefmt: "%H:%M:%S %Y-%m-%d"
    field_styles:
      levelname:
        color: cyan
        bold: True
      asctime:
        color: green
      name:
        color: blue

  # use `fmt_file` for file handler if viewing logs outside the terminal (e.g., with `cat`) to avoid ANSI symbols
  fmt_file:
    format: "%(levelname)s %(asctime)s %(name)s:      %(message)s"
    datefmt: "%H:%M:%S %Y-%m-%d"


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: fmt_console
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    maxBytes: 8388608 # bytes = 8 mb
    filename: placeholder  # the "placeholder" is changed on the startup with the value provided in src.system.logging.read_config
    backupCount: 4
    formatter: fmt_file

loggers:
  uvicorn.error:
    level: DEBUG
    handlers:
      - console
      - file
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers:
      - console
      - file
    propagate: no

root:
  level: DEBUG
  handlers:
    - console
    - file