version: 1
formatters:
  dev_console:
    class: coloredlogs.ColoredFormatter
    format: "%(levelname)s %(asctime)s %(name)s:      %(message)s"
    datefmt: "%H:%M:%S %Y-%m-%d"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: dev_console
    stream: ext://sys.stdout

loggers:
  uvicorn.error:
    level: DEBUG
    handlers:
      - console
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers:
      - console
    propagate: no

root:
  level: DEBUG
  handlers:
    - console